export declare function blockBodyScroll(className?: string): void;
export declare function exportCSV(csv: any, filename: string): void;
export declare function unblockBodyScroll(className?: string): void;
export declare function absolutePosition(element: HTMLElement, target: HTMLElement, gutter?: boolean): void;
export declare function addClass(element: HTMLElement, className: string | string[]): void;
export declare function addStyle(element: HTMLElement, styles: string | object): void;
export declare function appendChild(element: HTMLElement, target: HTMLElement): void;
export declare function calculateBodyScrollbarWidth(): number;
export declare function calculateScrollbarWidth(): number;
export declare function clearSelection(): void;
export declare function createElement(type: string, attributes?: object, ...children: any): HTMLElement | undefined;
export declare function fadeIn(element: HTMLElement, duration: number): void;
export declare function fadeOut(element: HTMLElement, duration: number): void;
export declare function find(element: HTMLElement, selector: string): any[];
export declare function findSingle(element: HTMLElement, selector: string): any;
export declare function focus(element: HTMLElement, options?: FocusOptions): void;
export declare function getAttribute(element: HTMLElement, name: string): any;
export declare function getBrowser(): object;
export declare function getCSSVariableByRegex(variableRegex: any): { name: string; value: string } | undefined;
export declare function getFirstFocusableElement(element: HTMLElement, selector?: string): any;
export declare function getFocusableElements(element: HTMLElement, selector?: string): any[];
export declare function getHeight(element: HTMLElement): number;
export declare function getHiddenElementDimensions(element: HTMLElement): { width?: number; height?: number };
export declare function getHiddenElementOuterHeight(element: HTMLElement): number;
export declare function getHiddenElementOuterWidth(element: HTMLElement): number;
export declare function getIndex(element: HTMLElement): number;
export declare function getInnerWidth(element: HTMLElement): number;
export declare function getLastFocusableElement(element: HTMLElement, selector?: string): any;
export declare function getNextElementSibling(element: HTMLElement, selector?: string): any;
export declare function getNextFocusableElement(element: HTMLElement, selector?: string): any;
export declare function getOffset(element: HTMLElement): { top: any; left: any };
export declare function getOuterHeight(element: HTMLElement, margin?: boolean): number;
export declare function getOuterWidth(element: HTMLElement, margin?: boolean): number;
export declare function getParentNode(element: HTMLElement): any;
export declare function getParents(element: HTMLElement, parents?: any[]): any[];
export declare function getPreviousElementSibling(element: HTMLElement, selector?: string): any;
export declare function getScrollableParents(element: HTMLElement): any[];
export declare function getSelection(): string | undefined;
export declare function getUserAgent(): string | undefined;
export declare function getViewport(): { width: number; height: number };
export declare function getWidth(el: HTMLElement): number;
export declare function getWindowScrollLeft(): number;
export declare function getWindowScrollTop(): number;
export declare function hasCSSAnimation(element: HTMLElement): boolean;
export declare function hasCSSTransition(element: HTMLElement): boolean;
export declare function hasClass(element: HTMLElement, className: string): boolean;
export declare function invokeElementMethod(element: HTMLElement, methodName: string, args: any): void;
export declare function isAndroid(): boolean;
export declare function isAttributeEquals(element: HTMLElement, name: string, value: any): boolean;
export declare function isAttributeNotEqual(element: HTMLElement, name: string, value: any): boolean;
export declare function isClickable(element: HTMLElement): boolean;
export declare function isClient(): boolean;
export declare function isElement(): boolean;
export declare function isExist(element: HTMLElement): boolean;
export declare function isFocusableElement(element: HTMLElement, selector?: string): any[];
export declare function isIOS(): boolean;
export declare function isTouchDevice(): boolean;
export declare function isVisible(element: HTMLElement): boolean;
export declare function nestedPosition(element: HTMLElement, level: number): void;
export declare function relativePosition(element: HTMLElement, target: HTMLElement): void;
export declare function removeClass(element: HTMLElement, className: string | string[]): void;
export declare function resolveUserAgent(): { browser: string; version: string };
export declare function scrollInView(container: HTMLElement, item: HTMLElement): void;
export declare function setAttribute(el: HTMLElement, attribute: string, value: any): void;
export declare function setAttributes(el: HTMLElement, attributes: object): void;
